pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') { 
            steps {
                sh 'mvn test' 
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml' 
                }
            }
        }
        stage('Tag') {
            steps {
                sh ' docker build -t app .'
                sh ' docker tag app thangqt/app:lastest'
                sh ' docker tag app thangqt/app:$BUILD_NUMBER'                
            }  
        }
        stage('Push'){
            steps {
                withDockerRegistry([ credentialsId: "dockerHub", url: "" ]) {
                    sh  'docker push thangqt/app:latest'
                    sh  'docker push thangqt/app:$BUILD_NUMBER' 
        }
            }
        }
    }
}
